### ISSUE TITLE
Layout/IndentationWidth is broken

### ISSUE THREAD

**Issue by penelopezone** [testdouble/standard#112] opened 2019-04-19 07:49 UTC
```ruby
class Foo
  def a
  rescue
  ensure
    a
  end
end
```

this fails with:

```
  hi.rb:3:3: Layout/IndentationWidth: Use 2 (not 0) spaces for indentation.
```

**Comment by searls** [comment] 2019-04-20 06:10
This appears to be a rubocop bug, but I can only repro it for empty methods, which makes it seem lower priority. This passes:

```ruby
class Foo
  def a
    nil
  rescue
  ensure
    a
  end
end
```

**Comment by will** [comment] 2019-07-10 13:05
I don’t know if this is the same thing, but when I try and make this indent "correctly" `Layout/IndentionWidth` is the rule that complains, and this is an open issue about that rule, so maybe??

``` ruby
    feed.entry(event,
      id: "urn:uuid:#{event["id"]}",
      url: url,
      published: Time.parse(event["createdAt"]),
      updated: Time.parse(event["createdAt"])) do |entry|
        entry.title(event["tag"].titleize)
        entry.author do |author|
          author.name "Citus Cloud"
      end
# …
```

gets changed to 

``` ruby
    feed.entry(event,
      id: "urn:uuid:#{event["id"]}",
      url: url,
      published: Time.parse(event["createdAt"]),
      updated: Time.parse(event["createdAt"])) do |entry|
      entry.title(event["tag"].titleize)
      entry.author do |author|
        author.name "Citus Cloud"
      end
# …
```

This is on v 0.1.0

**Comment by searls** [comment] 2019-07-10 14:52
Well, that sure seems bad. @will would you be willing or able to try digging into this?

**Comment by will** [comment] 2019-07-10 16:32
This is as far as I think I can get: 

It seems like it depends on where the **last** `end` is. You can move that one around, and the rest of the body above it will follow the indentation. Which seems a bit weird to me. (by follow I mean, I have my editor set to auto fix whatever errors, and when you move the `end`, it auto fixes the indentation to match where the last `end` is)

So if you have

``` ruby
a.method("a",
  id: 2,
  ok: 3) do |thing|
    thing.ok
    thing.other do |a|
      a.foo
    end
  end
```

and move that last `end` over to the left to spaces, the whole thing becomes

``` ruby
a.method("a",
  id: 2,
  ok: 3) do |thing|
  thing.ok
  thing.other do |a|
    a.foo
  end
end
```

This at least gives me a fix for this, and at most maybe means it’s not a bug at all and this is how it should be? I really don’t know.

**Comment by jmkoni** [comment] 2021-01-07 15:12
I was going through old issues and checked the state of this one. I put the original code in a file called test.rb:
```
class Foo
  def a
  rescue
  ensure
    a
  end
end
```

and it now fails with this glorious infinite loop.

```
be standardrb --fix test.rb
bundler: failed to load command: standardrb (/Users/jennifer/.rvm/gems/ruby-2.7.2@standard/bin/standardrb)
RuboCop::Runner::InfiniteCorrectionLoop: Infinite loop detected in /Users/jennifer/dev/standard/test.rb and caused by Layout/IndentationWidth -> Layout/IndentationWidth, Layout/RescueEnsureAlignment
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:304:in `check_for_infinite_loop'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:287:in `block in iterate_until_no_changes'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:286:in `loop'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:132:in `block in file_offenses'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:157:in `file_offense_cache'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:131:in `file_offenses'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:122:in `process_file'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:100:in `each'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:100:in `reduce'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:86:in `inspect_files'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/gems/rubocop-1.7.0/lib/rubocop/runner.rb:47:in `run'
  /Users/jennifer/dev/standard/lib/standard/runners/rubocop.rb:12:in `call'
  /Users/jennifer/dev/standard/lib/standard/cli.rb:18:in `run'
  /Users/jennifer/dev/standard/exe/standardrb:7:in `<top (required)>'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/bin/standardrb:23:in `load'
  /Users/jennifer/.rvm/gems/ruby-2.7.2@standard/bin/standardrb:23:in `<top (required)>'
```

@koic have you seen this particular collision before?

**Comment by dvandersluis** [comment] 2021-03-19 02:09
@jmkoni I opened rubocop/rubocop#9619 to fix the infinite loop.

**Comment by koic** [comment] 2021-03-19 04:50
I overlooked the mention 💦  @dvandersluis Thank you for working on this!

**Comment by jmkoni** [comment] 2021-03-19 12:36
@dvandersluis @koic thank you to you both :)

**Comment by jmkoni** [comment] 2021-04-21 14:45
Should be part of 1.05

**Closed by jmkoni** 2021-04-21 14:45 UTC
Labels: rubocop bug 🚨
