### ISSUE TITLE
Reconsider position on adopting trailing commas

### ISSUE THREAD

**Issue by penelopezone** [testdouble/standard#159] opened 2020-02-23 14:36 UTC
Hi Folks,

I am unsure trailing commas are the right solution, and I wrote a detailed report on the [`rubyfmt`](https://github.com/penelopezone/rubyfmt/issues/154) issue tracker that I'd love some discussion on.

**Comment by searls** [comment] 2020-02-27 01:59
So @penelopezone has decided in https://github.com/penelopezone/rubyfmt/issues/154 to eliminate trailing commas from rubyfmt.

It's long been a goal of both of us to keep these two projects in relative harmony with one another (ideally, running the same source listing through both tools would produce consistent results, such that standard could be winnowed down to just linting tasks and rubyfmt could take over for style/layout on a file-save-hook), and as a result I'm inclined to cascade her decision to standard as well.

Other reasons I support this decision:

* Selfishly, I don't personally like trailing commas so of course I don't mind it (see my comment in the above linked thread)

* Rubocop's defaults don't append trailing commas, and we've seen a handful of gnarly issues caused by our particular configuration including them

**Comment by searls** [comment] 2020-02-28 08:10
Fixed by a7156b14528f4b171567c528f6a2434a43b6e54a and released in v0.2.0

**Comment by thorncp** [comment] 2020-03-03 00:45
Looks like the current config doesn't take a stance on method calls. E.g. both of these are considered valid:

```ruby
doit(
  foo: "bar",
  baz: "qux"
)

doit(
  foo: "bar",
  baz: "qux",
)
```

Is that intentional?

**Comment by searls** [comment] 2020-03-03 01:07
Can you help me find the rubocop rule that would disallow the latter?

**Comment by thorncp** [comment] 2020-03-03 17:39
How about a PR? https://github.com/testdouble/standard/pull/160

**Closed** 2020-03-04 05:19 UTC
