### ISSUE TITLE
Auto correct for case indentation with assignment is weird

### ISSUE THREAD

**Issue by mtsmfm** [testdouble/standard#322] opened 2021-09-12 15:26 UTC
Let's say we have the following file foo.rb:

```ruby
foo12345 = if 1.next
             1
           elsif 2.next
             2
           elsif 3.next
             3
           end

bar12345 = case 0.next
           when 1.next
             1
           when 2.next
             2
           when 3.next
             3
           end

p foo12345
p bar12345
```

`standardrb --fix foo.rb` changes this file to:

```ruby
foo12345 = if 1.next
  1
elsif 2.next
  2
elsif 3.next
  3
end

bar12345 = case 0.next
           when 1.next
             1
           when 2.next
             2
           when 3.next
             3
end

p foo12345
p bar12345
```

I think 

```ruby
bar12345 = case 0.next
           when 1.next
             1
           when 2.next
             2
           when 3.next
             3
end
```

should be

```ruby
bar12345 = case 0.next
when 1.next
  1
when 2.next
  2
when 3.next
  3
end
```

Is this intentional?

## Additional info

This change can fix this alignment but Layout/CaseIndentation is disabled explicitly.
I'm not sure this patch can be accepted or not.

```diff
diff --git a/config/base.yml b/config/base.yml
index b9828fc..81e7d87 100644
--- a/config/base.yml
+++ b/config/base.yml
@@ -62,7 +62,8 @@ Layout/BlockEndNewline:
 Layout/CaseIndentation:
   # Disabled because IndentOneStep can't be configured for one-liner cases. See:
   # https://github.com/rubocop-hq/rubocop/issues/6447
-  Enabled: false
+  Enabled: true
+  EnforcedStyle: end
 
 Layout/ClosingHeredocIndentation:
   Enabled: true
```

**Comment by searls** [comment] 2021-09-13 12:56
Thanks for bringing this up. Let's discuss in #324

**Comment by searls** [comment] 2022-03-23 12:28
Marking as a dupe of #324

**Closed** 2022-03-23 23:43 UTC
